### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/bp-multiple-forum-post#3]
A primer: http://codex.wordpress.org/I18n_for_WordPress_Developers

Steps:
- [x] Make sure every string is wrapped in the appropriate `gettext` function, using the text domain 'bp-multiple-forum-post'. 
- [x] Add the textdomain to the plugin header
- [x] Set up i18n with `load_plugin_textdomain()`

**Comment by rjbaniel** [comment]
Addressed here: https://github.com/cuny-academic-commons/bp-multiple-forum-post/commit/6eed651cb764f534f525cd1e3f5a8e417ea23e37

One place I wasn't sure on, is where I change "forum" to "forums" for the posted in multiple forums string, because the original "forum" is generated by BP itself, and not my own plugin. Should I leave that be? Should I change the string replace with gettext functions for both forum and forums? In particular I'm not sure what to do about languages with more than one plural form. Any ideas?

**Comment by boonebgorges** [comment]
Looks pretty good!

> One place I wasn't sure on, is where I change "forum" to "forums" for the posted in multiple forums string, because the original "forum" is generated by BP itself, and not my own plugin. Should I leave that be? Should I change the string replace with gettext functions for both forum and forums? In particular I'm not sure what to do about languages with more than one plural form. Any ideas?

Yeah, this whole section would have to be rewritten to make it work properly. You can't do a `str_replace()` like this in all languages, and the `foo, bar, and baz` formation is not the same in different languages. I suggest going with something like the following instead:
1. First, if you detect that there is more than one forum, then build a brand new action string. Look at the way that BP does it, and mimic it. (All translatable strings must be full sentences; use placeholders and `sprintf()` as necessary.)
2. Instead of the `foo, bar, and baz` format, you'll just have to implode on `,`.

So it'll be something like this (this is partly pseudocode, but it'll give you the right idea):

```
$forum_links = array();
foreach ( $duplicate_activities as $dupe ) {
    $forum_links[] = sprintf( '<a href="%s">%s</a>', esc_url( $dupe_url ), esc_html( $dupe_name ) );
}

if ( count( $forum_links ) === 1 ) {
    $action = sprintf(
         __( '%1$s posted the topic %2$s in the group forum %3$s', 'bp-multiple-forum-post' ),
        $user_link,
        $topic_link,
        implode( ', ', $forum_links )
    );
} else {
    $action = sprintf(
         __( '%1$s posted the topic %2$s in the group forums %3$s', 'bp-multiple-forum-post' ),
        $user_link,
        $topic_link,
        implode( ', ', $forum_links )
    );
}
```

I know this is kinda brutal. Getting internationalization right is hard :)

**Comment by rjbaniel** [comment]
Thanks for the help here, Boone.

I think I've done it here: https://github.com/cuny-academic-commons/bp-multiple-forum-post/commit/52e807f9676f1bee206216e9b59537c614033332

What I decided to do was leave the string completely alone if there weren't any duplicates of the activity/topic. If there were, I rebuilt it from scratch along the lines of what you posted, borrowing from how bbPress does it. One thing I did differently was I had the forum names for the duplicate topics link directly to the topic in that forum, instead of the forum homepage. The topic name links directly to the topic in the original forum, and the name of the original forum links to that forum's homepage. Does that make sense? I think it's what users would expect to happen.

It's hard but I think it makes you write better code!

**Comment by boonebgorges** [comment]
Awesome - I think this looks good. Thanks, @rjbaniel !

**Comment by boonebgorges** [comment]
Oops, closed this a bit too soon. Missing a couple strings:
- 'Show All' in `bpmfp_show_other_groups()`
- 'Sorry, there was a problem verifying your request' in `bpmfp_create_duplicate_topics()`

Also, there's one place where you're using the 'bbpress' text domain. I know it's the same string as bbPress uses, but technically, WP doesn't support the use of multiple text domains in a single plugin. (Also, if bbPress changes the string, we'll lose the translation.) We should use 'bp-multiple-forum-post' throughout.

**Comment by rjbaniel** [comment]
Good catches - thanks Boone. Here's a commit with those changes: https://github.com/cuny-academic-commons/bp-multiple-forum-post/commit/cb57931bcadcb35333018343963f9c511c321373

**Comment by boonebgorges** [comment]
Thanks!
