### ISSUE TITLE
Proper output escaping

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/bp-multiple-forum-post#4]
I noticed a number of places where user-generated content - like group names - is displayed on the front end, without being escaped. Let's fix this. Rules of thumb: 
- use `esc_html()` for text that's echoed in such a way that it's displayed as the content of a HTML element (eg: `<h2><?php echo esc_html( $group->name ); ?></h2>`)
- use `esc_attr()` for text that needs to be sanitized for use in element attributes (eg `<input name="foo" value="<?php echo esc_attr( $group->slug ); ?>">`)
- use `esc_url()` for URLs, pretty much whenever they need to be echoed to the screen (there are exceptions where it's better to use `esc_url_raw()` - see https://kovshenin.com/2012/esc_url-vs-esc_url_raw/)

**Comment by rjbaniel** [comment]
Addressed here: https://github.com/cuny-academic-commons/bp-multiple-forum-post/commit/6eed651cb764f534f525cd1e3f5a8e417ea23e37

**Comment by boonebgorges** [comment]
Looking good

**Comment by modelm** [comment]
Because of this change https://github.com/cuny-academic-commons/bp-multiple-forum-post/commit/6eed651cb764f534f525cd1e3f5a8e417ea23e37#diff-510c3663aa41187468817522a3a7c765R123 - when markup is in the content or body of a post, it is escaped in the duplicate posts resulting in this:

![screen shot 2016-12-30 at 12 12 42 pm](https://cloud.githubusercontent.com/assets/330857/21569266/50ae7d84-ce89-11e6-8717-f2f41194ab5c.png)
![screen shot 2016-12-30 at 12 12 37 pm](https://cloud.githubusercontent.com/assets/330857/21569269/544ea144-ce89-11e6-9dfc-3f6f2319db22.png)

Is there a reason the escaping is necessary here or is this a bug?

**Comment by boonebgorges** [comment]
Hi @modelm - Thanks for the ticket. It looks like a bug; I'd noted in that changeset that content should not be output-escaped on the way into the database, but it looks like it was never rolled out. See https://github.com/cuny-academic-commons/bp-multiple-forum-post/blob/master/bp-multiple-forum-post.php#L142

@rjbaniel Could you have a look? Be sure to test with rich-text content.

**Comment by modelm** [comment]
OK - I have already removed the esc_attr() for title & content in our fork, so if that's the only required change and you want a PR just let me know.

**Comment by boonebgorges** [comment]
Yup, I'm pretty sure that's all that's required.
